### ISSUE TITLE
Latest version GTM

### ISSUE THREAD

**Issue by jorgb90** [breezefront/module-breeze-mirasvit-gtm#1]
Hi,

Is this fully compatible with the latest module version of Mirasvit?

Thanks,
Jorg

**Comment by vovayatsyuk** [comment]
Sorry, I don't know. We do not track updates of third-party modules.

**Comment by jorgb90** [comment]
@vovayatsyuk How is this created then? Can I provide you with latest version to check? Or is there no support?

**Comment by vovayatsyuk** [comment]
Did you try it already? What's not working?
